new-window -d -n "claude"
split-window -d -h -t "claude"
send-keys -t "claude.2" "claude" Enter

new-window -d -n "server"
send-keys -t "server" "npm run dev" Enter

split-window -d -h -l 80 "git fetch && git st && read -p 'Press enter to continue...'"
